-- MySQL Script generated by MySQL Workbench
-- mer. 27 juil. 2022 10:04:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dbpermis
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbpermis
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbpermis` DEFAULT CHARACTER SET utf8 ;
USE `dbpermis` ;

-- -----------------------------------------------------
-- Table `dbpermis`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpermis`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(255) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `dbpermis`.`permis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpermis`.`permis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL UNIQUE,
  `description` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `dbpermis`.`image`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbpermis`.`image` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `path` LONGTEXT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- Article
INSERT INTO permis (name, description) VALUES ("Permis B", "Ma super descreiption");
INSERT INTO permis (name, description) VALUES ("Permis C", "Ma super description");

-- User
-- password 123456
INSERT INTO user (email, username, password) VALUES ( "christian.fillette@gmail.com", "titeuf", "$2b$10$wVDCS1rhJLzjXwX.K9drF.CCz0UeU8k/EHv2TG06deCs0tmGLUfcW");